[pairs.personal.source]
type = "imap"
host_cmd = "op item get \"Personal Mail\" --fields host"
port = 993
username_cmd = "op item get \"Personal Mail\" --fields username"
password_cmd = "op item get \"Personal Mail\" --fields password"

[pairs.personal.destination]
type = "maildir"
path = "./Maildir/personal"  # TODO: support ~

